<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDwlMKid\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDwlMKid/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDwlMKid.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDwlMKid\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDwlMKid\appAppKernelProdContainer([
    'container.build_hash' => 'DwlMKid',
    'container.build_id' => '95e533a6',
    'container.build_time' => 1761400122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDwlMKid');
