<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container63UPwcm\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container63UPwcm/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container63UPwcm.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container63UPwcm\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container63UPwcm\appAppKernelProdContainer([
    'container.build_hash' => '63UPwcm',
    'container.build_id' => '681a918f',
    'container.build_time' => 1761400055,
], __DIR__.\DIRECTORY_SEPARATOR.'Container63UPwcm');
